# Generated by Django 4.2.11 on 2024-03-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_date', models.DateField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
